language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source
  - if [ "5.5" == $TRAVIS_PHP_VERSION ]; then pyrus install pear/PHP_CodeSniffer; fi
  - phpenv rehash

script:
  - if [ "5.5" == $TRAVIS_PHP_VERSION ]; then phpcs --standard=PSR2 src/; fi
  - phpunit -c phpunit.xml.dist

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
