language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source
  - phpenv rehash

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/
  - ./vendor/bin/phpunit -c phpunit.xml.dist

sudo: false

notifications:
  email:
    recipients:
      - dev-ci@maxmind.com
    on_success: change
    on_failure: always
